version: '3'

services:
  minerva-api:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'nest-api'
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=nest-api

volumes:
  database:
